### PR TITLE
Nubis init

### PR DESCRIPTION
**Pull request by limed**
Add script to initialize nubis repo and create the necessary folders and .gitignore files

### CODE REVIEW

**Comment by tinnightcap** [comment]
As we discussed last week I think this would be better if it incorporated the nubis-skel project instead of creating all of the directories manually. This way we are not maintaining the same logic in two places. Also this maintains the current method that people are already used to of using the nubis-skel project to bootstrap their projects. Feel free to ping me on IRC is you want to discuss.

**Comment by limed** [comment]
I wanted to create a PR so that I don't lose track of it, I'm happy to relocate this to another location

**Comment by gozer** [comment]
Yeah, what @tinnightcap jd said makes a lot of sense to me too. That's one of the reason nubis-skel exists in the first place.

**Comment by tinnightcap** [comment]
As we discussed:
 * Download release tarball of nubis-skel
 * Extract directory structure with files
 * copy -dist parameters file
 * copy or generate or add to .gitignore file

Let me know if you need more details.

**Pull request closed without merging**
